# Server configuration
server:
  context-path: /micro
  port: 8080

# Spring properties
spring:
  application:
     name: micro-customer
     
     cloudant:
        username: 54585bd1-ddd1-4a7d-aef0-eede5fb1336b-bluemix
        password: 668ca1fda724cb99c601a6bedfdd617ec34b383727ec9fdc299936251cec30eb
        host: 54585bd1-ddd1-4a7d-aef0-eede5fb1336b-bluemix.cloudantnosqldb.appdomain.cloud
        protocol: https
        port: 443
        database: customers

jwt:
  enabled: false
  key: l6kHLmBzbzdBi8eznmg-nGP3pZihFpLgie0K-SKEUARXzyG5yJ7nnZoFPVL_MvoJckcoRslQZlxsNZpVruKqrP0s-m6YDaKw4Ody8lZbPmQ7wU0Mc1561J01VH55s4apg_TvnOJ6xn8sEfid3gPbvXntIb0hokVtopG5Zaam2wfyMuBlzqhQ42TtL51yZOym5NLad4_WtZUG9kM204K7OgLHFfUABpWD4ocBF7uQrebcO4cwqlVI6N_A_252TdEkfOyh_vG4yxO0h88LxaGSXj0iKFpO4q6md7bFMjzdehtPKiqWktKg02QyAjq-PRcrSiWBZfh2w6JIkU7g8kS5YQ
